### ISSUE TITLE
You can export an EXPORT sub

### ISSUE THREAD

**Issue by lizmat** [FCO/Configuration#2]
Not really an issue, but an idea: you *can* export an `EXPORT` sub, so the example code could look like:

```raku
use v6.d;

class RootConfig does Configuration::Node {
    has Int      $.a;
    has Int      $.b      = $!a * 2;
    has Int      $.c      = $!b * 3;
}

use Configuration RootConfig;
```
See https://github.com/lizmat/Slangify/blob/main/lib/Slangify.rakumod for an example on how to do that.

**Comment by FCO** [comment]
Thanks! That sounds as a good idea! I'll try that after work and see how it feels, thanks!

**Comment by FCO** [comment]
Done, thanks @lizmat !
